### PR TITLE
A few more edits--please see comments too...

### PR DESCRIPTION
**Pull request by mcSamuelDataSci**

### CODE REVIEW

**Comment by holtzy** [comment]
Thx so much!

**Comment by holtzy** [comment]
Hi Samuel,

What comments are you talking about?

**Comment by mcSamuelDataSci** [comment]
Comments to the commit, like [here](https://github.com/mcSamuelDataSci/data_to_viz/commit/3c33d7774c012e2bab0be44dd18e4046d0eedc51).  Do these show up on your side?

**Comment by holtzy** [comment]
No I don't see these comments on my side... I don't know how to see all of them

**Comment by holtzy** [comment]
Could you put them as issues? Or in the comment section below the post?
Thx so much for your help!

**Pull request merged**
